### ISSUE TITLE
Useragent on static sites (next.js export)

### ISSUE THREAD

**Issue by lukio3** [quentin-sommer/react-useragent#125]
Hi Quentin,

Thanks for the package!

I have UserAgent working perfectly in development for my Next.js app, I used your example _app.js file to get started.

However, when I come to export to a static site the useragent doesn't work (i'm guessing because this is only available client-side).

Is there a work-around this or is useragent just generally unavailable for statically generated sites?

Thanks!

Update: Next.js docs https://nextjs.org/docs/advanced-features/static-html-export
> With next export, we build an HTML version of your app. At export time we will run the getInitialProps in your pages. The req and res fields of the context object will be empty objects during export as there is no server running.

**Comment by quentin-sommer** [comment]
Hi,

You have the right intuition: the user-agent is given by, well, the user accessing the website. When you build locally your html files there is no way to know what the user-agent will be. 

To be able to use this library correctly you'll need to do 2 things:

- Hardcode a fallback when the user-agent string does not exist
- Move the provider usage in a render method instead of `getInitialProps`. This way it will run even when the page is pre rendered by next.js:

Here's an example:
```jsx
const App = props => {
  // I just googled an example of a desktop user-agent
  const ua = typeof window === 'undefined'
    ? 'Mozilla/5.0 (X11; CrOS x86_64 8172.45.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.64 Safari/537.36'
    : window.navigator.userAgent
  return(
     <UserAgentProvider ua={ua}>
       <div>{/* rest of your App */}</div>
     </UserAgentProvider>
  )
}
```
Maybe `window` is defined in next.js build context but `navigator` is not or maybe only `userAgent` is not defined but that's the gist

Best

**Comment by quentin-sommer** [comment]
I'm closing this. Feel free to re-open if needed!
