### ISSUE TITLE
Including Oculus Browser

### ISSUE THREAD

**Issue by jazilzaim** [quentin-sommer/react-useragent#359]
With more increase of VR headset sales, it would be nice to include Oculus Browser. Is there any chance someone like me can assist through a PR to include the Oculus Browser in this library?

**Comment by quentin-sommer** [comment]
Hi, you can already access its value directly through the parsing library using the  `returnFullParser` prop
https://github.com/faisalman/ua-parser-js#methods

```jsx
<UserAgent returnFullParser>
  {parser => (
    {parser.getBrowser().name == "Oculus Browser" && 
      <p>Oculus specific content</p>
    }
  )}
</UserAgent>
```

Or were you thinking about adding a prop like `<UserAgent oculus>`?

**Comment by jazilzaim** [comment]
Yea I was referring to adding a prop potentially

**Comment by quentin-sommer** [comment]
I think there are a lot of commonly used browsers which don't have a pre-computed prop for, like Vivaldi,  Mobile Safari or Brave for example.

I'm not sure about adding one because it feels arbitrary. 
You could implement it building a new context hook on top of the existing one to provide the prop?
```jsx
```

**Comment by jazilzaim** [comment]
Alright thank you! :)
