### ISSUE TITLE
Next 9 warns opted-out Automatic Prerendering

### ISSUE THREAD

**Issue by Tanapruk** [quentin-sommer/react-useragent#54]
Based on your example [next example](https://github.com/zeit/next.js/blob/canary/examples/with-react-useragent/pages/_app.js),
The example is using `getInitialProps`,this  gets warn.
```
Warning: You have opted-out of Automatic Prerendering due to `getInitialProps` in `pages/_app`.

 Read more: https://err.sh/next.js/opt-out-automatic-prerendering
```

Is there anyway to comply with the warning?

Thanks,

**Comment by quentin-sommer** [comment]
Hi,

This library dynamically detect the user agent when the pages are rendered. It is not possible to pre-render the pages before because there is no way to know what the user-agent of the visiting users will be. So in short: it is not possible to comply with the warning

If you want to pre-render a next.js page you won't be able to use this library on the page.

Hope this answers your question!

**Comment by Tanapruk** [comment]
Thank you for answering me.

Prerendering is before knowing what is the loading user agent is.  If we render after knowing the user agent then it is not a prerender. One way or another then.

**Comment by quentin-sommer** [comment]
I gues you could use it only client side without server-side rendering, it might work for your use case
