### ISSUE TITLE
Consider renaming to UserAgentConsumer ?

### ISSUE THREAD

**Issue by revskill10** [quentin-sommer/react-useragent#7]
Following Apollo naming, should we rename `UserAgent` to `UserAgentConsumer` to access `parser info` ?

**Comment by quentin-sommer** [comment]
Hi, I'm not a Apollo user myself so I don't know the community consensus on their naming conventions. What I do know is that I would prefer avoiding non vital breaking changes like this to keep the library nice and simple!

**Comment by revskill10** [comment]
@quentin-sommer It made sense to make clear about *Provider and *Consumer. For client usage, it's just a renaming to Consumer , no changing to behaviour, so i think in this case, it's fine to rename.

**Comment by quentin-sommer** [comment]
I get that adding the Consumer prefix would make it be a bit clearer. 

However, I don't think it would add any real value to the library. It will create a breaking change because as you say people will need to rename the import. This is not something I want to do now. 
Maybe if the library grows enough to require a new major version we might be able to add the renaming in it but right now I don't want to add it just for the sake of it.

I'm closing this issue but if you have anything to add feel free to comment back!

Quentin
